### PR TITLE
Fix creation of edges at boundary

### PR DESCRIPTION
**Pull request by david94133**
Thanks for the library, it is great!

### CODE REVIEW

**Comment by david94133** [comment]
Are the tests supposed to pass? They seem to be seg faulting.  For the AppVeyor tests, I was unable to find any information to use in troubleshooting.

For the Travis tests, the seg fault is apparently in the "voronoi_test_one_site" test. (The one before that passed). That test works fine on my machine.

So I don't have any idea why they are not passing.

**Comment by JCash** [comment]
Thx @david94133!

It's time for me to take a look at the reported issues, and in this case the actual PR has some issues.
(As it stands, the tets crashes, and it contains commented out tests, and added prints...)

Do you have some test data so I can reproduce the issue?

**Comment by david94133** [comment]
Sorry JCash, I can't figure it out. All of the test cases pass on my machine, but fail with continuous integration. I spent several hours trying to figure out why, but was unsuccessful. All of the commits on July 22nd and July 23rd are me narrowing down the tests to figure out where it is failing, but that did not provide any useful information. All of the commits from the 22nd and 23rd can be deleted, but I don't know how.

Regarding the actual fix, it applies to all diagrams, so no new test cases are required. The edges of each cell, that lie on the border, were not create correctly; you obviously knew this when writing it since there are comments noting it ("gap->edge = current->edge; // not really true"). Rather than create new edges at the border, previously the program re-used edges, so a cell on the border was missing an edge on the border, but another edge was duplicated.

The PR on July 20th is a fix to properly initialize "new_edge->sites[1] = NULL;". Edges on the border only have one site, since the other side is out of the bounding box.

Sorry I no longer have the code I used to visualize the edges, plus it was very tied to my application, so not really useful to anyone else. If you draw the diagram by drawing only edges, you will see the problem (missing edges at the border).

I'd love to know why the integration tests are failing. It was very frustrating! I setup Travis integration on my account especially for this, but the output logs didn't help.

**Comment by JCash** [comment]
> Regarding the actual fix, it applies to all diagrams, so no new test cases are required
For both issues and new feratures, a test should be added.
This case should be easily testable: If the points of the graph edge doesn't match with the points of the edge, then it's the wrong edge.

What is your actual use case?
Are you using the graph edges to traverse the edges?

I don't recall why I opted for this particular implementation, but I think `jcv_diagram_get_edges()` returns actual edges from the voronoi diagram. Whereas the border edges are "made up".

If I want to stick with that implementation, then the border graph edges' edge should be 0, since they're "made up".

If I want `jcv_diagram_get_edges()` to return all edges, then I should create new edges during the gap fill step.

**Comment by david94133** [comment]
My use case includes drawing lines for edges, not just a fill for entire cells. The current code doesn't just omit edges, but actively assigns duplicate edges. A single cell that contains an edge on the boundary will have 2 edges with the same endpoints -- see line 1183 and 1213, or search for "not really true"

Not sure I understand the difference between "actual" edges and "made up" edges. The cells should be bounded by edges, no? The area contained by the cells is defined by the edges. If you walk the edges and extract points and fill a cell, the problem will not be visible, but if you use edges themselves it is.

On boundary corners you need at least one "made up" edge, in order to capture the corner point.

My PR was an attempt to fix that, but it fails the tests. (I also used various memory debugging tools on my own machine [malloc guard, malloc scribble, zombie objects] and couldn't find a failure case, but the integration tests fail. I tried bisecting the tests, but the failure comes at a point that was unrelated to my fixes. I've moved on to other things, so if this fix isn't of interest to you, just close it.

**Comment by JCash** [comment]
I've now added unique edges to the border graph edges.
And this also means the jcv_diagram_get_edges() will return the list of all edges, including the border ones.

This is now merged into master, and released as v0.5.0 (b352e14)

So this PR is obsolete now and I will thus close it.
Thanks for pointing out the issue @david94133 !

**Pull request closed without merging**
